# Generated by Django 4.2.4 on 2023-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
    ]
